# Generated by Django 4.2 on 2023-04-28 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='favorites',
            field=models.ManyToManyField(through='favamealapi.FavoriteMeal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='favorites',
            field=models.ManyToManyField(through='favamealapi.FavoriteRestaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
